### ISSUE TITLE
Question about the invTrans in the visualization code for automix

### ISSUE THREAD

**Issue by mrbulb** [Westlake-AI/openmixup#16]
Hi, thank you for your great work.
I found that the invTrans in  the visualization code for automix use cifar dataset's mean & std by default.
Will it work when i input the imagenet images?

https://github.com/Westlake-AI/openmixup/blob/90dab92464e94ac5c4139c37f07ed21df9c2affb/openmixup/models/classifiers/automix_V1plus.py#L353

**Comment by Lupin1998** [comment]
Hi, @mrbulb, thanks for your attention to our work. In `OpenMixup`, we adopt the same mean & std for all datasets by default, thus `invTrans` is suitable for visualizing mixed samples of [AutoMix](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/imagenet/automix) on ImageNet-1K. Besides, we will release the weights, logs, and visualization results (AutoMix and SAMix) on ImageNet-1K for reference in the next few days. Please feel free to ask me if you have more questions.

**Comment by mrbulb** [comment]
> Hi, @mrbulb, thanks for your attention to our work. In `OpenMixup`, we adopt the same mean & std for all datasets by default, thus `invTrans` is suitable for visualizing mixed samples of [AutoMix](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/imagenet/automix) on ImageNet-1K. Besides, we will release the weights, logs, and visualization results (AutoMix and SAMix) on ImageNet-1K for reference in the next few days. Please feel free to ask me if you have more questions.

I seems that the mean & std for cifar100 and imagenet is different according to the configs. So I'm still confused 😂 

https://github.com/Westlake-AI/openmixup/blob/90dab92464e94ac5c4139c37f07ed21df9c2affb/configs/classification/_base_/datasets/cifar100/sz32_bs100.py#L5

https://github.com/Westlake-AI/openmixup/blob/90dab92464e94ac5c4139c37f07ed21df9c2affb/configs/classification/_base_/datasets/imagenet/basic_sz224_4xbs64.py#L10

**Comment by Lupin1998** [comment]
> > Hi, @mrbulb, thanks for your attention to our work. In `OpenMixup`, we adopt the same mean & std for all datasets by default, thus `invTrans` is suitable for visualizing mixed samples of [AutoMix](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/imagenet/automix) on ImageNet-1K. Besides, we will release the weights, logs, and visualization results (AutoMix and SAMix) on ImageNet-1K for reference in the next few days. Please feel free to ask me if you have more questions.
> 
> I seems that the mean & std for cifar100 and imagenet is different according to the configs. So I'm still confused 😂
> 
> https://github.com/Westlake-AI/openmixup/blob/90dab92464e94ac5c4139c37f07ed21df9c2affb/configs/classification/_base_/datasets/cifar100/sz32_bs100.py#L5
> 
> https://github.com/Westlake-AI/openmixup/blob/90dab92464e94ac5c4139c37f07ed21df9c2affb/configs/classification/_base_/datasets/imagenet/basic_sz224_4xbs64.py#L10

Sorry, that's my mistake and thanks for pointing out this bug. Although the inverse of mean & std in `invTrans` are based on the mean & std of CIFAR, but it also works for ImageNet visualization (e.g., mixed samples and MIM predictions). We will fix this bugs in the next commit.

**Comment by Lupin1998** [comment]
Thanks again for using and improving our framework! I will close this issue if there is no more question. If you have more questions, you can reopen it or start a new issue.
