### ISSUE TITLE
SAMix Configs for TinyImageNet

### ISSUE THREAD

**Issue by aswathn1** [Westlake-AI/openmixup#2]
Hey, would it be possible to get SAMix Resnet 18 config files for TinyImageNet? I'm trying to adapt the CIFAR-100 config to Tiny but I'm running into shape mismatch issues. Thank you.

**Comment by Lupin1998** [comment]
Hi Radhakrishnan, I have updated SAMix configs for TinyImageNet-200. Please refer to `docs/model_zoos/Model_Zoo_sup.md` for experiment results (on updating). Thanks for using OpenMixup.
