### ISSUE TITLE
Have you tried to train DeiT-Tiny with something mixup variants?

### ISSUE THREAD

**Issue by ChenMnZ** [Westlake-AI/openmixup#23]
Great works! I would like to know if you train DeiT-Tiny with something mixup variants by openmixup. 
If yes, could you share some results?

**Comment by Lupin1998** [comment]
Hi @ChenMnZ, thanks for your question. Unfortunately, we have only trained DeiT-Tiny with the official training receipts (Mixup with alpha=0.8 and CutMix with alpha=1.0) on `OpenMixup` and get `74.50` top-1 accuracy. If you are interested in benchmarking mixup variants with DeiT-Tiny, we can cooperate in conducting relevant experiments in ImageNet-1K. Please feel free to ask me if you have more questions or contact me directly, e.g., via e-mail or WeChat (`Lupin_1998`).

**Comment by Lupin1998** [comment]
I close this issue if there is no more question. You can reopen it or start a new issue if you have more questions.
