### ISSUE TITLE
Where can we find the Resnet fine-tuning config file for A2MIM?

### ISSUE THREAD

**Issue by wang-tf** [Westlake-AI/openmixup#27]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

In this [page](https://github.com/Westlake-AI/openmixup/tree/main/configs/selfsup/a2mim), I can not find the **Fine-tuning Config** for **ResNet-50**. There is a likely config(**configs/benchmarks/classification/imagenet/r50_rsb_a2_ft_sz224_8xb256_cos_fp16_ep100.py**) in the directory. Is it the right cofnig file?

**Comment by Lupin1998** [comment]
Thanks for your issue. We will fix this bug and update the [README](https://github.com/Westlake-AI/openmixup/tree/main/configs/selfsup/a2mim) for A2MIM in the next commit. Here are the correct file path for ResNet-50 fine-tuning: [fine-tune 100ep](https://github.com/Westlake-AI/openmixup/blob/main/configs/benchmarks/classification/imagenet/r50_rsb_a2_ft_sz224_8xb256_cos_fp16_ep100.py) and [fine-tune 300ep](https://github.com/Westlake-AI/openmixup/blob/main/configs/benchmarks/classification/imagenet/r50_rsb_a2_ft_sz224_8xb256_cos_fp16_ep100.py).
