### ISSUE TITLE
Where will I get the pretrained code for moganet?

### ISSUE THREAD

**Issue by M-SunRise** [Westlake-AI/openmixup#30]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

\[here\]

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmcls` folder.
   \[here\]

**Comment by Lupin1998** [comment]
Hi, @M-SunRise. Thanks for your attention to our [MogaNet](https://arxiv.org/abs/2211.03295). Could you please describe your question in detail? We have provided [configs](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/imagenet/moganet/) and the source code [moganet.py](https://github.com/Westlake-AI/openmixup/blob/main/openmixup/models/backbones/moganet.py), which can be used to reproduce results of MogaNet. As for checkpoints and logs of pre-trained models of MogaNet, we plan to release them a few months later. Please free to ask me if you have further questions.

**Comment by Lupin1998** [comment]
Hello @M-SunRise, thanks for your attention and patience. We have uploaded the release of weights and logs of [MogaNet](https://arxiv.org/abs/2211.03295) in [moganet-in1k-weights](https://github.com/Westlake-AI/openmixup/releases/tag/moganet-in1k-weights). We hope you will find it useful. I will close this issue in two days if there are no more questions. Please feel free to contact me for discussion.

**Comment by Lupin1998** [comment]
I closed this issue if there is no more question. You can reopen it or start a new issue if you have more questions. Thanks again for your attention.
