### ISSUE TITLE
Can you share the resnet 18 "vanila" config for Tiny-imagenet?

### ISSUE THREAD

**Issue by jeeyung** [Westlake-AI/openmixup#39]
Hello! Thanks for sharing the great repo!
I coudn't find the  resnet 18 "vanila" config for Tiny-imagenet. Could you share it if you have?

**Comment by Lupin1998** [comment]
Hi, @jeeyung. Thanks for using OpenMixup! You can modify `model.mix_mode` to change the mixup method. Taking [r18_mixups_CE_none.py](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/tiny_imagenet/mixups/basic/r18_mixups_CE_none.py) as an example, please modify line 11 as follows:
```python
model = dict(mix_mode="vanilla")
```
Moreover, I can modify an existing config file with [auto_train.py](). For example, you can generate new config files of `mixup` with `alpha=1` and `alpha=0.2` based on ResNet-18 on Tiny-ImageNet by running [auto_train_mixups.py](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/tiny_imagenet/mixups/auto_train_mixups.py).
```bash
# modify line 19 in auto_train_mixups.py
python configs/classification/tiny_imagenet/mixups/auto_train_mixups.py
```
I hope this will help you. Feel free to ask me if more questions occur.

**Comment by Lupin1998** [comment]
I will close this issue if there is no more question. Feel free to open a new issue when new questions occur.
