### ISSUE TITLE
Issue with training model using Tiny ImageNet/ImageNet

### ISSUE THREAD

**Issue by YF16443** [Westlake-AI/openmixup#46]
Dear Authors,

Thank you for your excellent work on your GitHub repository. I'm currently trying to train the model using Tiny ImageNet/ImageNet, but I've encountered an error that states the missing file `data/TinyImageNet/meta/train'_ labeled.txt`. I've checked the documentation for adding new datasets, but couldn't find any information on how to correct this issue. Could you please provide me with some guidance on how the Tiny ImageNet/ImageNet dataset structure should be or provide a simple demo/example to show me how to train the model using given configuration `configs/classification/tiny_imagenet/mixups/basic/r18_mixups_CE_none.py`?

Thank you for your time and help.

**Comment by Lupin1998** [comment]
Hi, @YF16443. Thanks for your question 👍 and sorry for the late reply. We apologise for the bug of `missing file data/TinyImageNet/meta/train'_ labeled.txt` in TinyImageNet dataset. This bug stems from wrong paths to meta files in [tiny_imagenet/sz64_bs100.py](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/_base_/datasets/tiny_imagenet/sz64_bs100.py). We have fixed this bug, and you can find meta files for TinyImageNet in [dataset](https://github.com/Westlake-AI/openmixup/releases/tag/dataset). Please place the meta files and datasets as follows, and you can train the given config on TinyImageNet. I hope this will help you!

```
openmixup
├── configs
├── data
│   ├── meta [used for 'ImageList' dataset]
│   ├── cifar10
│   ├── cifar100
│   ├── ImageNet
│   │   ├── train
│   │   ├── val
│   ├── TinyImageNet
│   │   ├── train
│   │   ├── val
```

**Comment by Lupin1998** [comment]
Hi, I will close this issue if my answers are helpful and you have no more questions. Feel free to open another issue when new problems occur!

**Comment by YF16443** [comment]
Hi, Sure, the issue is resolved. Thank you very much for your help.

> Hi, I will close this issue if my answers are helpful and you have no more questions. Feel free to open another issue when new problems occur!
