### ISSUE TITLE
Pre-training weight problem

### ISSUE THREAD

**Issue by xiaobaitubaibaibai** [Westlake-AI/openmixup#52]
I really appreciate your project, but I have a question about whether there is a pre-training weight

**Comment by Lupin1998** [comment]
Hi, @xiaobaitubaibaibai, thanks for appreciating OpenMixup. Could you please specify your question (e.g., which pre-trained weights you are looking for)? We have released some weights, but there are also some not collected pre-trained models.

**Comment by xiaobaitubaibaibai** [comment]
> Hi, @xiaobaitubaibaibai, thanks for appreciating OpenMixup. Could you please specify your question (e.g., which pre-trained weights you are looking for)? We have released some weights, but there are also some not collected pre-trained models.

Pre-training weights for training MogaNet

**Comment by xiaobaitubaibaibai** [comment]
> Hi, @xiaobaitubaibaibai, thanks for appreciating OpenMixup. Could you please specify your question (e.g., which pre-trained weights you are looking for)? We have released some weights, but there are also some not collected pre-trained models.

Thank you for your reply

**Comment by Lupin1998** [comment]
As for pre-trained weights of MogaNet, please refer to [moganet-in1k-weights](https://github.com/Westlake-AI/openmixup/releases/tag/moganet-in1k-weights). Meanwhile, you can find more trained weights of MogaNet for various downstream tasks in [Westlake-AI/MogaNet](https://github.com/Westlake-AI/MogaNet). I hope these will be helpful to you.

**Comment by xiaobaitubaibaibai** [comment]
Thank you very much！Thank you for your replay!

**Comment by Lupin1998** [comment]
I will close this issue if there is no more question.

**Comment by xiaobaitubaibaibai** [comment]
Yes,Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Siyuan ***@***.***&gt;; 
发送时间: 2023年7月12日(星期三) 凌晨4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Westlake-AI/openmixup] Pre-training weight problem (Issue #52)





 
I will close this issue if there is no more question.
