### ISSUE TITLE
Simmim for CIFAR data config does not exist

### ISSUE THREAD

**Issue by Debrove** [Westlake-AI/openmixup#55]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Hi! I want to run simmim on CIFAR, but it seems the dataset config (configs/selfsup/_base_/datasets/cifar10/simmim_sz192_bs64.py) does not exist.

Looking forward to your reply! Thank you!

**Comment by Lupin1998** [comment]
Hi, @Debrove, thanks for your issue. Sorry for the late reply. We have fixed this bug in the latest commit. You can try to reproduce the results on CIFAR-100, as we haven't conducted such benchmarks of masked modeling methods. Feel free to raise a new issue if another problem occurs.
