### ISSUE TITLE
where can i find published (pretrained) models for tiny imagenet?

### ISSUE THREAD

**Issue by tumble-weed** [Westlake-AI/openmixup#56]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Thank you for the comprehensive library. Its capabilities are a little overwhelming to absorb at first. I was led to this repo from the paperswithcode tiny imagenet benchmark. I am just looking for a pretrained model of resnet18 on tiny imagenet. Usually such links are part of the [model zoo](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/model_zoos/Mixup_sup.md), but i think the structure is a little different here.

 Is there any link to such a model? I see on [getting started](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/get_started.md) there is facility to publish a model, so is there any listing of publicly available such models? 

thanks again for your work.

**Comment by Lupin1998** [comment]
Hi, @tumble-weed, please refer to [README](https://github.com/Westlake-AI/openmixup/tree/main/configs/classification/imagenet/moganet/README.md) in MogaNet configs. You can download all files from [openmixup-moganet-in1k-weights](https://github.com/Westlake-AI/openmixup/releases/tag/moganet-in1k-weights), [timm-moganet-in1k-weights](https://github.com/Westlake-AI/MogaNet/releases/tag/moganet-in1k-weights), or **Baidu Cloud**: [MogaNet (z8mf)](https://pan.baidu.com/s/1d5MTTC66gegehmfZvCQRUA?pwd=z8mf). I will close this issue, and you can open a new issue if there are more questions.
