### ISSUE TITLE
Broken mmcv Documentation Links

### ISSUE THREAD

**Issue by f-amerehi** [Westlake-AI/openmixup#59]
The mmcv documentation links in the [about Configs](https://github.com/Westlake-AI/openmixup/blob/main/docs/en/tutorials/0_config.md) and runner link are broken.

**Comment by Lupin1998** [comment]
Hi, @f-amerehi. Thanks for pointing out the typo, and we have fixed it in the latest commit. I will close the issue if there are no more bugs.
