### ISSUE TITLE
[Feature] Recommend add MixPro method (ICLR2023).

### ISSUE THREAD

**Issue by fistyee** [Westlake-AI/openmixup#60]
### 推荐更新
Thanks to open source repositories for contributions. We recommend updating our method MixPro (ICLR2023) in this repository, especially the method **MaskMix** for image mixing which is as plug-and-play as mixup and has a significant improvement in training ViT's based methods.

**Comment by Lupin1998** [comment]
Hi, @fistyee. Thanks for your attention on OpenMixup and recommend an excellent work of Transformer-based mixup augmentation. We are working on adding MixPro and will update as soon as possible. We would appreciate any contributions that recommend more open-source mixup methods or contribute code implementations to OpenMixup. Please watch us for the latest update.
