### ISSUE TITLE
Implement migratory A2MIM

### ISSUE THREAD

**Issue by zhenyuZ-HUST** [Westlake-AI/openmixup#63]
Can you provide a simple code for A2MIM? The current situation is that changing the design of A2MIM requires a deep reading of the code of openmixup, which is inefficient and time-consuming for most people.

**Comment by Lupin1998** [comment]
Hi, @zhenyuZ-HUST. Thanks for your suggestion, and sorry for the late reply. It might be inconvenient for researchers to migrate A2MIM from the openmixup codebase, and we are too busy to reimplement A2MIM as SimMIM. But you can migrate A2MIM as CMID ([paper](https://ieeexplore.ieee.org/abstract/document/10105625), [code](https://github.com/NJU-LHRS/official-CMID)) for downstream tasks. Feel free to contact us if you have some problems with A2MIM.
